using UnityEngine;
using UnityEditor;
using System.IO;
using System.Text;
using System.Collections.Generic;

namespace UnityMCP
{
    /// <summary>
    /// Generates a UIReferences.cs file that gives type-safe access
    /// to every named UI element created by MCP.
    /// 
    /// Usage in your game code:
    ///   var refs = GetComponent&lt;UIReferences&gt;();
    ///   refs.LoginButton.onClick.AddListener(OnLogin);
    /// </summary>
    public static class UIReferencesGenerator
    {
        private const string OutputFolder = "Assets/UI/Generated";

        public static void Generate(GameObject root, ComponentNode tree)
        {
            var fields   = new List<FieldInfo>();
            CollectFields(root.transform, tree, fields);

            if (fields.Count == 0) return;

            var className = SanitizeName(root.name) + "References";
            var code      = BuildCode(className, fields, root.name);

            Directory.CreateDirectory(OutputFolder);
            var path = Path.Combine(OutputFolder, $"{className}.cs");
            File.WriteAllText(path, code);
            AssetDatabase.Refresh();

            // Attach component to the root GameObject
            var existing = root.GetComponent(className);
            if (existing == null)
            {
                // Component won't resolve until after compile; just log
                Debug.Log($"[MCP] Generated {path}. Add '{className}' component to {root.name} after compile.");
            }
        }

        // ── Field collection ──────────────────────────────────
        private static void CollectFields(Transform t, ComponentNode node, List<FieldInfo> list)
        {
            if (node.type != UiComponentType.Panel)
            {
                list.Add(new FieldInfo
                {
                    FieldName  = SanitizeFieldName(node.name),
                    TypeName   = CSharpType(node.type),
                    Path       = GetPath(t),
                    GoName     = node.name,
                });
            }

            int childIdx = 0;
            foreach (Transform child in t)
            {
                if (childIdx < node.children.Length)
                    CollectFields(child, node.children[childIdx++], list);
            }
        }

        // ── Code builder ──────────────────────────────────────
        private static string BuildCode(string className, List<FieldInfo> fields, string rootName)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// AUTO-GENERATED by Unity MCP — do not edit manually.");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UnityEngine.UI;");
            sb.AppendLine("using TMPro;");
            sb.AppendLine();
            sb.AppendLine("[System.Serializable]");
            sb.AppendLine($"public class {className} : MonoBehaviour");
            sb.AppendLine("{");
            sb.AppendLine($"    // Generated from prefab: {rootName}");
            sb.AppendLine();

            foreach (var f in fields)
                sb.AppendLine($"    [SerializeField] public {f.TypeName} {f.FieldName};");

            sb.AppendLine();
            sb.AppendLine("#if UNITY_EDITOR");
            sb.AppendLine("    [UnityEditor.MenuItem(\"CONTEXT/" + className + "/Auto-assign References\")]");
            sb.AppendLine($"    private static void AutoAssign(UnityEditor.MenuCommand cmd)");
            sb.AppendLine("    {");
            sb.AppendLine($"        var c = ({className})cmd.context;");
            foreach (var f in fields)
                sb.AppendLine($"        c.{f.FieldName} = c.transform.Find(\"{f.Path}\")?.GetComponent<{f.TypeName}>();");
            sb.AppendLine("        UnityEditor.EditorUtility.SetDirty(c);");
            sb.AppendLine("    }");
            sb.AppendLine("#endif");
            sb.AppendLine("}");

            return sb.ToString();
        }

        // ── Helpers ───────────────────────────────────────────
        private static string CSharpType(UiComponentType t) => t switch
        {
            UiComponentType.Button     => "UnityEngine.UI.Button",
            UiComponentType.Image      => "UnityEngine.UI.Image",
            UiComponentType.Text       => "TMPro.TextMeshProUGUI",
            UiComponentType.InputField => "TMPro.TMP_InputField",
            UiComponentType.ScrollView => "UnityEngine.UI.ScrollRect",
            UiComponentType.Toggle     => "UnityEngine.UI.Toggle",
            UiComponentType.Slider     => "UnityEngine.UI.Slider",
            _                          => "UnityEngine.RectTransform",
        };

        private static string GetPath(Transform t)
        {
            var parts = new List<string>();
            var cur   = t;
            while (cur.parent != null && cur.parent.parent != null)
            {
                parts.Insert(0, cur.name);
                cur = cur.parent;
            }
            return string.Join("/", parts);
        }

        private static string SanitizeName(string s)     => System.Text.RegularExpressions.Regex.Replace(s, @"[^a-zA-Z0-9]", "");
        private static string SanitizeFieldName(string s)
        {
            var clean = SanitizeName(s);
            return char.ToLower(clean[0]) + clean[1..];
        }

        private class FieldInfo
        {
            public string FieldName;
            public string TypeName;
            public string Path;
            public string GoName;
        }
    }
}
